/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import javax.swing.JLabel;



/**
 *
 * @author angel
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Filosofo1 = new javax.swing.JLabel();
        Filosofo2 = new javax.swing.JLabel();
        Filosofo3 = new javax.swing.JLabel();
        Filosofo4 = new javax.swing.JLabel();
        Filosofo5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        floor1 = new javax.swing.JLabel();
        floor2 = new javax.swing.JLabel();
        floor3 = new javax.swing.JLabel();
        floor4 = new javax.swing.JLabel();
        floor5 = new javax.swing.JLabel();
        floor6 = new javax.swing.JLabel();
        floor7 = new javax.swing.JLabel();
        floor8 = new javax.swing.JLabel();
        floor9 = new javax.swing.JLabel();
        floor10 = new javax.swing.JLabel();
        floor11 = new javax.swing.JLabel();
        floor12 = new javax.swing.JLabel();
        floor13 = new javax.swing.JLabel();
        floor14 = new javax.swing.JLabel();
        floor15 = new javax.swing.JLabel();
        floor16 = new javax.swing.JLabel();
        floor17 = new javax.swing.JLabel();
        floor18 = new javax.swing.JLabel();
        floor19 = new javax.swing.JLabel();
        floor20 = new javax.swing.JLabel();
        floor21 = new javax.swing.JLabel();
        floor22 = new javax.swing.JLabel();
        floor23 = new javax.swing.JLabel();
        floor24 = new javax.swing.JLabel();
        floor25 = new javax.swing.JLabel();
        floor26 = new javax.swing.JLabel();
        floor27 = new javax.swing.JLabel();
        floor28 = new javax.swing.JLabel();
        floor29 = new javax.swing.JLabel();
        floor30 = new javax.swing.JLabel();
        floor31 = new javax.swing.JLabel();
        floor32 = new javax.swing.JLabel();
        floor33 = new javax.swing.JLabel();
        floor34 = new javax.swing.JLabel();
        floor35 = new javax.swing.JLabel();
        floor36 = new javax.swing.JLabel();
        floor37 = new javax.swing.JLabel();
        floor38 = new javax.swing.JLabel();
        floor39 = new javax.swing.JLabel();
        floor40 = new javax.swing.JLabel();
        floor41 = new javax.swing.JLabel();
        floor42 = new javax.swing.JLabel();
        floor43 = new javax.swing.JLabel();
        floor44 = new javax.swing.JLabel();
        floor45 = new javax.swing.JLabel();
        floor46 = new javax.swing.JLabel();
        floor47 = new javax.swing.JLabel();
        floor48 = new javax.swing.JLabel();
        floor49 = new javax.swing.JLabel();
        floor50 = new javax.swing.JLabel();
        floor51 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        ConF1 = new javax.swing.JLabel();
        ConF2 = new javax.swing.JLabel();
        ConF3 = new javax.swing.JLabel();
        ConF4 = new javax.swing.JLabel();
        ConF5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Filosofo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f1.png"))); // NOI18N
        jPanel1.add(Filosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 30, -1));

        Filosofo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f2.png"))); // NOI18N
        jPanel1.add(Filosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        Filosofo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f3.png"))); // NOI18N
        jPanel1.add(Filosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        Filosofo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f4.png"))); // NOI18N
        jPanel1.add(Filosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        Filosofo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/f5.png"))); // NOI18N
        jPanel1.add(Filosofo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fork2.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fork3.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fork2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fork2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fork3.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/table.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, -1));

        floor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        floor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        floor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        floor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        floor5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        floor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        floor7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        floor8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        floor9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        floor10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        floor11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        floor12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        floor13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        floor14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        floor15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        floor16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        floor17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        floor18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        floor19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        floor20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        floor21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        floor22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        floor23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        floor24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        floor25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        floor26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        floor27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        floor28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        floor29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor29, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        floor30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        floor31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        floor32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        floor33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        floor34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        floor35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        floor36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        floor37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        floor38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        floor39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor39, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        floor40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        floor41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        floor42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor42, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        floor43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor43, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        floor44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        floor45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        floor46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor46, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        floor47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        floor48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        floor49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor49, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        floor50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor50, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        floor51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jPanel1.add(floor51, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        ConF1.setText("Filosofo 1");

        ConF2.setText("Filosofo 2");

        ConF3.setText("Filosofo 3");

        ConF4.setText("Filosofo 4");

        ConF5.setText("Filosofo 5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ConF1)
                        .addGap(28, 28, 28)
                        .addComponent(ConF2)
                        .addGap(40, 40, 40)
                        .addComponent(ConF3)
                        .addGap(18, 18, 18)
                        .addComponent(ConF4)
                        .addGap(32, 32, 32)
                        .addComponent(ConF5)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConF1)
                    .addComponent(ConF2)
                    .addComponent(ConF3)
                    .addComponent(ConF4)
                    .addComponent(ConF5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Finalizar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
        
        /*Arreglo para los filosofos */
        JLabel Filosofos [];
        Filosofos = new JLabel[5];
        Filosofos[0] = Filosofo1;
        Filosofos[1] = Filosofo2;
        Filosofos[2] = Filosofo3;
        Filosofos[3] = Filosofo4;
        Filosofos[4] = Filosofo5;
       
          
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConF1;
    private javax.swing.JLabel ConF2;
    private javax.swing.JLabel ConF3;
    private javax.swing.JLabel ConF4;
    private javax.swing.JLabel ConF5;
    private javax.swing.JLabel Filosofo1;
    private javax.swing.JLabel Filosofo2;
    private javax.swing.JLabel Filosofo3;
    private javax.swing.JLabel Filosofo4;
    private javax.swing.JLabel Filosofo5;
    private javax.swing.JLabel floor1;
    private javax.swing.JLabel floor10;
    private javax.swing.JLabel floor11;
    private javax.swing.JLabel floor12;
    private javax.swing.JLabel floor13;
    private javax.swing.JLabel floor14;
    private javax.swing.JLabel floor15;
    private javax.swing.JLabel floor16;
    private javax.swing.JLabel floor17;
    private javax.swing.JLabel floor18;
    private javax.swing.JLabel floor19;
    private javax.swing.JLabel floor2;
    private javax.swing.JLabel floor20;
    private javax.swing.JLabel floor21;
    private javax.swing.JLabel floor22;
    private javax.swing.JLabel floor23;
    private javax.swing.JLabel floor24;
    private javax.swing.JLabel floor25;
    private javax.swing.JLabel floor26;
    private javax.swing.JLabel floor27;
    private javax.swing.JLabel floor28;
    private javax.swing.JLabel floor29;
    private javax.swing.JLabel floor3;
    private javax.swing.JLabel floor30;
    private javax.swing.JLabel floor31;
    private javax.swing.JLabel floor32;
    private javax.swing.JLabel floor33;
    private javax.swing.JLabel floor34;
    private javax.swing.JLabel floor35;
    private javax.swing.JLabel floor36;
    private javax.swing.JLabel floor37;
    private javax.swing.JLabel floor38;
    private javax.swing.JLabel floor39;
    private javax.swing.JLabel floor4;
    private javax.swing.JLabel floor40;
    private javax.swing.JLabel floor41;
    private javax.swing.JLabel floor42;
    private javax.swing.JLabel floor43;
    private javax.swing.JLabel floor44;
    private javax.swing.JLabel floor45;
    private javax.swing.JLabel floor46;
    private javax.swing.JLabel floor47;
    private javax.swing.JLabel floor48;
    private javax.swing.JLabel floor49;
    private javax.swing.JLabel floor5;
    private javax.swing.JLabel floor50;
    private javax.swing.JLabel floor51;
    private javax.swing.JLabel floor6;
    private javax.swing.JLabel floor7;
    private javax.swing.JLabel floor8;
    private javax.swing.JLabel floor9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private static class Jlabel {

        public Jlabel() {
        }
    }
}
